# Generated by Django 3.1.2 on 2022-04-08 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0049_auto_20220409_0025'),
        ('sent_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentitems',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 0, 24, 56, 81034)),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 4, 9, 0, 24, 56, 81034))),
                ('active', models.BooleanField(default=True)),
                ('cartitems', models.ManyToManyField(blank=True, null=True, to='toners.TonerDetails')),
            ],
        ),
    ]
