# Generated by Django 4.2.1 on 2023-06-21 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentitems',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 21, 9, 39, 548505)),
        ),
    ]
