# Generated by Django 4.2.3 on 2023-08-13 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_items', '0003_alter_sentitems_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='dispatched',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sentitems',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 13, 19, 10, 476325)),
        ),
    ]
