# Generated by Django 4.2.3 on 2023-08-13 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_items', '0004_cartitem_dispatched_cartitem_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sentitems',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 13, 21, 30, 317910)),
        ),
    ]
