# Generated by Django 3.1.2 on 2022-08-22 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_items', '0005_auto_20220822_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='model_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='received_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='serial_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 20, 23, 36, 819577)),
        ),
        migrations.AlterField(
            model_name='sentitems',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 20, 23, 36, 819577)),
        ),
    ]
