# Generated by Django 3.1.2 on 2022-08-22 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_items', '0006_auto_20220822_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='send_to',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 20, 47, 33, 224511)),
        ),
        migrations.AlterField(
            model_name='sentitems',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 20, 47, 33, 224511)),
        ),
    ]
