# Generated by Django 3.1.2 on 2022-08-22 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0109_auto_20220822_2056'),
        ('sent_items', '0008_auto_20220822_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 20, 56, 31, 101090)),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='issued_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prosecutions.prosecutions'),
        ),
        migrations.AlterField(
            model_name='sentitems',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 20, 56, 31, 101090)),
        ),
    ]
