# Generated by Django 3.1.2 on 2022-08-22 17:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0091_auto_20220822_2110'),
        ('sent_items', '0009_auto_20220822_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='toner_printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.items'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 21, 10, 26, 411532)),
        ),
        migrations.AlterField(
            model_name='sentitems',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 21, 10, 26, 411532)),
        ),
    ]
