# Generated by Django 3.1.2 on 2022-08-23 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_items', '0011_auto_20220822_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='issued_to',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='model_no',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='toner_printer',
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 20, 11, 24, 151472)),
        ),
        migrations.AlterField(
            model_name='sentitems',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 20, 11, 24, 151472)),
        ),
    ]
