# Generated by Django 3.1.2 on 2022-09-01 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sent_items', '0012_auto_20220823_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 20, 10, 21, 34517)),
        ),
        migrations.AlterField(
            model_name='sentitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sent_items.cartitem'),
        ),
        migrations.AlterField(
            model_name='sentitems',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 20, 10, 21, 34517)),
        ),
    ]
