# Generated by Django 3.1.2 on 2022-09-06 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0095_auto_20220906_1931'),
        ('sent_items', '0013_auto_20220901_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='tproduct',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='iproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemdetails'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 19, 31, 14, 33583)),
        ),
        migrations.AlterField(
            model_name='sentitems',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 19, 31, 14, 34582)),
        ),
    ]
