# Generated by Django 3.1.2 on 2022-09-07 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_items', '0019_auto_20220907_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 22, 25, 15, 653118)),
        ),
        migrations.AlterField(
            model_name='sentitems',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 22, 25, 15, 653118)),
        ),
    ]
