# Generated by Django 5.0 on 2024-03-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contracts_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='employee_number',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
