# Generated by Django 5.0 on 2024-03-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contracts_pdf_file2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='pdf_file2',
        ),
    ]
