# Generated by Django 5.0 on 2024-06-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_remove_contracts_pdf_file2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='warranty_years',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, null=True),
        ),
    ]
