# Generated by Django 5.0 on 2024-06-25 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_contracts_warranty_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='warranty_end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='warranty_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
