# Generated by Django 5.0 on 2024-07-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_alter_contracts_warranty_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='pdf_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='pdfs/contracts/'),
        ),
    ]
