# Generated by Django 3.1.2 on 2022-02-19 08:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0031_auto_20220219_1239'),
        ('prosecutions', '0050_auto_20220219_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toner_model', models.CharField(max_length=10, null=True)),
                ('total_qty', models.PositiveIntegerField(default=0, null=True)),
                ('remaining_qty', models.PositiveIntegerField(default=0, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 2, 19, 12, 39, 2, 590782))),
                ('toner_printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items')),
            ],
        ),
        migrations.CreateModel(
            name='TonerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In-Stock', 'In-Stock'), ('Out-of-Stock', 'Out-of-Stock')], default='In-Stock', max_length=30)),
                ('employee_name', models.CharField(max_length=30, null=True)),
                ('employee_designation', models.CharField(max_length=30, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 2, 19, 12, 39, 2, 590782))),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prosecutions.prosecutions')),
                ('toner_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toners.toners')),
            ],
        ),
    ]
