# Generated by Django 5.0 on 2024-03-06 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('prosecutions', '0116_remove_prosecutions_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toner_model', models.CharField(max_length=100, null=True)),
                ('total_qty', models.PositiveIntegerField(default=0, null=True)),
                ('remaining_qty', models.PositiveIntegerField(default=0, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('toner_printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items')),
            ],
        ),
        migrations.CreateModel(
            name='TonerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In-Stock', 'In-Stock'), ('Out-of-Stock', 'Out-of-Stock')], default='In-Stock', max_length=30)),
                ('employee_name', models.CharField(max_length=300, null=True)),
                ('employee_designation', models.CharField(max_length=300, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_dispatched', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_to', models.ForeignKey(default='31', on_delete=django.db.models.deletion.CASCADE, to='prosecutions.prosecutions')),
                ('toner_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toners.toners')),
            ],
            options={
                'ordering': ['-date_dispatched'],
            },
        ),
    ]
