# Generated by Django 3.1.2 on 2022-03-19 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0009_auto_20220319_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonerdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 13, 34, 9, 446399, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='toners',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 13, 34, 9, 446399, tzinfo=utc)),
        ),
    ]
