# Generated by Django 3.1.2 on 2022-03-19 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0010_auto_20220319_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonerdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 9, 38, 23, 997957, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='toners',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 9, 38, 23, 982334, tzinfo=utc)),
        ),
    ]
