# Generated by Django 3.1.2 on 2022-03-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0027_auto_20220319_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonerdetails',
            name='created',
            field=models.DateTimeField(default='03/19/22:55:2022:14:55:45'),
        ),
        migrations.AlterField(
            model_name='toners',
            name='created',
            field=models.DateTimeField(default='03/19/22:55:2022:14:55:45'),
        ),
    ]
