# Generated by Django 3.1.2 on 2022-03-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0028_auto_20220319_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonerdetails',
            name='created',
            field=models.DateTimeField(default='2022-19-03 14:58:27'),
        ),
        migrations.AlterField(
            model_name='toners',
            name='created',
            field=models.DateTimeField(default='2022-19-03 14:58:27'),
        ),
    ]
