# Generated by Django 3.1.2 on 2022-03-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0030_auto_20220319_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonerdetails',
            name='created',
            field=models.DateTimeField(default='2022-19-03 15:18:16:15:18:16Z'),
        ),
        migrations.AlterField(
            model_name='toners',
            name='created',
            field=models.DateTimeField(default='2022-19-03 15:18:16'),
        ),
    ]
