# Generated by Django 3.1.2 on 2022-03-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0031_auto_20220319_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonerdetails',
            name='created',
            field=models.DateTimeField(default='2022YYY-22M-03/19/22D 15H:22M:39S15:22:39Z'),
        ),
        migrations.AlterField(
            model_name='toners',
            name='created',
            field=models.DateTimeField(default='2022YYY-22M-03/19/22D 15H:22M:39S15:22:39Z'),
        ),
    ]
