# Generated by Django 3.1.2 on 2022-03-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0033_auto_20220319_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonerdetails',
            name='created',
            field=models.DateTimeField(default='2022-27-03/19/22 15:27:35Z'),
        ),
        migrations.AlterField(
            model_name='toners',
            name='created',
            field=models.DateTimeField(default='2022-27-03/19/22 15:27:3515:27:35Z'),
        ),
    ]
