# Generated by Django 3.1.2 on 2022-03-19 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0043_auto_20220319_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonerdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 15, 46, 55, 299664, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='toners',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 15, 46, 55, 299664, tzinfo=utc)),
        ),
    ]
