# Generated by Django 3.1.2 on 2022-09-06 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0061_auto_20220906_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonerdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 20, 20, 50, 531815)),
        ),
        migrations.AlterField(
            model_name='toners',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 20, 20, 50, 531815)),
        ),
    ]
