# Generated by Django 3.1.2 on 2022-09-06 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0063_auto_20220906_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonerdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 20, 28, 40, 226048)),
        ),
        migrations.AlterField(
            model_name='toners',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 20, 28, 40, 226048)),
        ),
    ]
