# Generated by Django 3.1.2 on 2022-09-07 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toners', '0065_auto_20220907_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonerdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 20, 32, 48, 586181)),
        ),
        migrations.AlterField(
            model_name='toners',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 20, 32, 48, 586181)),
        ),
    ]
