# Generated by Django 3.1.2 on 2020-11-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=50, null=True)),
                ('model_no', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('total_qty', models.IntegerField(default=0, null=True)),
                ('rem_qty', models.IntegerField()),
                ('status', models.CharField(choices=[('In-Stock', 'In-Stock'), ('Out-of-Stock', 'Out-of-Stock')], max_length=30, null=True)),
            ],
        ),
    ]
