# Generated by Django 5.0 on 2024-03-06 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prosecutions', '0116_remove_prosecutions_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('total_qty', models.PositiveIntegerField(default=0, null=True)),
                ('remaining_qty', models.PositiveIntegerField(default=0, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=500, null=True)),
                ('tag_no', models.CharField(max_length=500, null=True)),
                ('room_tag', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('In-Stock', 'In-Stock'), ('Out-of-Stock', 'Out-of-Stock'), ('issued-to', 'issued-to')], default='In-stock', max_length=30)),
                ('employee_name', models.CharField(max_length=500, null=True)),
                ('employee_designation', models.CharField(max_length=500, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_dispatched', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(blank=True, default='', null=True, upload_to='pdfs/')),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prosecutions.prosecutions')),
                ('model_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items')),
            ],
            options={
                'ordering': ['-date_dispatched'],
            },
        ),
    ]
