# Generated by Django 3.1.2 on 2020-11-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.CharField(choices=[('In-Stock', 'In-Stock'), ('Out-of-Stock', 'Out-of-Stock'), ('available', 'available')], max_length=30, null=True),
        ),
    ]
