# Generated by Django 5.0 on 2024-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='pdf_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='pdfs/items/'),
        ),
    ]
