# Generated by Django 5.0 on 2024-03-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_itemdetails_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='pdf_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='items/'),
        ),
    ]
