# Generated by Django 3.1.2 on 2020-11-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20201115_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.CharField(default='in-stock', max_length=30),
        ),
    ]
