# Generated by Django 5.0 on 2024-06-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_itemdetails_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='pdf_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='pdfs/itemdetails/'),
        ),
    ]
