# Generated by Django 3.1.2 on 2020-11-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20201115_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.CharField(choices=[('In-Stock', 'In-Stock'), ('Out-of-Stock', 'Out-of-Stock'), ('available', 'available')], default='in-stock', max_length=30),
        ),
    ]
