# Generated by Django 5.0 on 2024-07-01 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_contracts_pdf_file'),
        ('items', '0004_alter_itemdetails_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='lpo_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contracts'),
        ),
    ]
