# Generated by Django 3.1.2 on 2020-11-19 20:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0021_auto_20201120_0036'),
        ('items', '0004_auto_20201115_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='rem_qty',
        ),
        migrations.RemoveField(
            model_name='items',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='items',
            name='status',
        ),
        migrations.AddField(
            model_name='items',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=50, null=True)),
                ('rem_qty', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('In-Stock', 'In-Stock'), ('Out-of-Stock', 'Out-of-Stock'), ('issued-to', 'issued-to')], default='in-stock', max_length=30)),
                ('employee_name', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prosecutions.prosecutions')),
                ('model_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items')),
            ],
        ),
    ]
