# Generated by Django 5.0 on 2024-07-08 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_contracts_pdf_file'),
        ('items', '0005_itemdetails_lpo_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='lpo_no',
            field=models.ForeignKey(blank=True, default='17', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contracts'),
        ),
    ]
