# Generated by Django 5.2 on 2025-05-17 18:24

import django.db.models.deletion
import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_contracts_pdf_file'),
        ('items', '0007_alter_itemdetails_lpo_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='lpo_no',
            field=models.ForeignKey(default=items.models.get_default_lpo, on_delete=django.db.models.deletion.CASCADE, to='contracts.contracts'),
        ),
    ]
