# Generated by Django 3.1.2 on 2020-11-25 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20201125_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 21, 7, 40, 709387)),
        ),
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 21, 7, 40, 708390)),
        ),
        migrations.AlterField(
            model_name='items',
            name='total_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
