# Generated by Django 3.1.2 on 2020-12-01 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_auto_20201129_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 12, 21, 19, 245711)),
        ),
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 12, 21, 19, 245711)),
        ),
        migrations.AlterField(
            model_name='items',
            name='total_qty',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
