# Generated by Django 3.1.2 on 2020-12-03 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_auto_20201201_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 14, 43, 18, 350184)),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='status',
            field=models.CharField(choices=[('In-Stock', 'In-Stock'), ('Out-of-Stock', 'Out-of-Stock'), ('issued-to', 'issued-to')], default='In-stock', max_length=30),
        ),
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 14, 43, 18, 350184)),
        ),
    ]
