# Generated by Django 3.1.2 on 2022-02-17 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_auto_20201204_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='employee_designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='tag_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 21, 46, 21, 114464)),
        ),
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 21, 46, 21, 114464)),
        ),
    ]
