# Generated by Django 3.1.2 on 2022-02-27 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0034_auto_20220227_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 13, 49, 22, 283146)),
        ),
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 13, 49, 22, 283146)),
        ),
        migrations.AlterField(
            model_name='items',
            name='model_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
