# Generated by Django 3.1.2 on 2022-03-19 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0038_auto_20220319_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 13, 14, 53, 352388)),
        ),
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 13, 14, 53, 352388)),
        ),
    ]
