# Generated by Django 3.1.2 on 2022-04-08 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0080_auto_20220319_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 22, 31, 42, 566104)),
        ),
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 22, 31, 42, 565105)),
        ),
    ]
