# Generated by Django 3.1.2 on 2022-09-07 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0098_auto_20220906_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 19, 52, 59, 461952)),
        ),
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 19, 52, 59, 461952)),
        ),
    ]
