# Generated by Django 4.2.1 on 2023-05-20 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(default='none', max_length=30)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
