# Generated by Django 3.1.2 on 2020-11-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0002_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='prosecutions',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
