# Generated by Django 3.1.2 on 2020-11-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0003_auto_20201102_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='location',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
