# Generated by Django 3.1.2 on 2020-11-04 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0006_auto_20201104_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 22, 9, 22, 169383)),
        ),
    ]
