# Generated by Django 3.1.2 on 2020-11-15 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0007_auto_20201104_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 20, 59, 25, 685648)),
        ),
    ]
