# Generated by Django 3.1.2 on 2020-11-19 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0011_auto_20201115_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 23, 14, 2, 678578)),
        ),
    ]
