# Generated by Django 3.1.2 on 2020-11-19 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0019_auto_20201119_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 23, 53, 44, 800672)),
        ),
    ]
