# Generated by Django 3.1.2 on 2020-11-19 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0020_auto_20201119_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 0, 36, 22, 246073)),
        ),
    ]
