# Generated by Django 3.1.2 on 2020-11-19 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0022_auto_20201120_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 0, 43, 37, 768822)),
        ),
    ]
