# Generated by Django 3.1.2 on 2020-11-20 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0023_auto_20201120_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 10, 26, 54, 520179)),
        ),
    ]
