# Generated by Django 3.1.2 on 2020-11-20 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0025_auto_20201120_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 12, 47, 57, 583607)),
        ),
    ]
