# Generated by Django 3.1.2 on 2020-11-26 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0034_auto_20201126_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 22, 43, 17, 143559)),
        ),
    ]
