# Generated by Django 3.1.2 on 2020-11-27 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0038_auto_20201127_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 12, 8, 54, 952080)),
        ),
    ]
