# Generated by Django 3.1.2 on 2020-11-29 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0040_auto_20201127_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 22, 30, 41, 159544)),
        ),
    ]
