# Generated by Django 3.1.2 on 2020-11-29 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0042_auto_20201129_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 22, 33, 30, 85361)),
        ),
    ]
