# Generated by Django 3.1.2 on 2020-12-01 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0044_auto_20201129_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 12, 21, 19, 230089)),
        ),
    ]
