# Generated by Django 3.1.2 on 2020-12-04 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0046_auto_20201203_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 13, 5, 44, 278679)),
        ),
    ]
