# Generated by Django 3.1.2 on 2022-02-17 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0047_auto_20201204_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 21, 46, 21, 114464)),
        ),
    ]
