# Generated by Django 3.1.2 on 2022-02-21 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0050_auto_20220219_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 21, 31, 58, 55310)),
        ),
    ]
