# Generated by Django 3.1.2 on 2022-02-27 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0053_auto_20220227_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 13, 49, 22, 267518)),
        ),
    ]
