# Generated by Django 3.1.2 on 2022-03-19 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0095_auto_20220319_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 16, 5, 53, 909879)),
        ),
    ]
