# Generated by Django 3.1.2 on 2022-04-08 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0099_auto_20220319_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 22, 31, 42, 559195)),
        ),
    ]
