# Generated by Django 4.2.1 on 2023-05-20 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0113_auto_20220901_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prosecutions',
            name='location',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
