# Generated by Django 3.1.2 on 2022-09-07 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosecutions', '0118_auto_20220907_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecutions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 20, 32, 48, 554933)),
        ),
    ]
